const messages = {
  loginSuccessful: ["Login successful"],
  msg_empty_param: ["Please send data"],
  userNotRegisterHere: ["You are not register here"],
  internalServerError: ["Internal Server Error"],
  invalidCredentials: ["Invalid email or password"],
  msgDataFound: ["Data Found"],
  msgDataNotFound: ["Data not Found"],
  msgUserNotFound: ["User not Found"],
  msgCategoryNotFound: ["Category not Found"],
  msgOtherNotFound: ["Other user not Found"],
  msgUserActivatederror: ["User active unsuccessfully, please try again"],
  msgUserDeactivatederror: ["User deactive unsuccessfully, please try again"],
  accountdeactivated: ["Your account has been deactivated by admin"],
  msgDeactiveStatusUpdateSuccess: ["User has been deactivated successfully."],
  msgRejectStatusUpdateSuccess: ["Expert has been rejected successfully."],
  msgActiveStatusUpdateSuccess: ["User has been activated successfully."],
  msgApproveStatusUpdateSuccess: ["Expert has been Approved successfully."],
  profileUpdateSuccessfully: ["Profile updated successfully"],
  signupSuccessfully: ["Signup successfully"],
  otpsend: ["Otp send successfully"],
  accountAlreadyExists: ["account number already exists"],
  addressAddSuccessfully: ["address add successfully..!!"],
  mobileNotRegistered: ["Mobile number registered with us."],
  otpResendSuccess: ["Otp resend successfully"],
  wrongotpsend: ["Invalid otp"],
  wrongPassword: ["old password wrong...!!"],
  otpverifysuccess: ["Otp verified successfully"],
  // eslint-disable-next-line no-dupe-keys
  profileUpdateSuccessfully: ["Profile update successfully"],
  PasswordNotCorrect: [" password doesn't match"],
  forgotNewpasswordUpdate: ["Password updated successfully"],
  newOldPassword: ["Old password not correct"],
  profileImageUpdate: ["profile image update successfully...!!"],
  wrongotp: ["worng otp Enter....!!"],
  updateNewForgetPassword: ["password update successfully...!!"],
  newOldPasswordNotCorrect: ["Old password not correct"],
  contactUsMsg: ["Contact massage send successfully...!!"],
  deleteAccount: ["account delete successfully...!!"],
  bioaddsuccessfully: ["bio add successfully."],
  // eslint-disable-next-line no-dupe-keys
  wrongotp: ["worng otp Enter...!!"],
  OtpUpdated: ["otp updated successfully"],
  otpResendUnSuccess: ["error sending otp"],
  // eslint-disable-next-line no-dupe-keys
  accountdeactivated: ["Your account has been deactivated"],
  ErrorFindViewCount: ["Sorry, we couldn't find any data to display. Please try again later or check your connection",],
  msgEmailExist: ["Email Already Exist"],
  PasswordUpdatedSuccessfully: ["Password Updated Successfully"],
  AccoundDeleted: ["Your account has been deactivated"],
  NoSchoolFound: ["No School Found"],
  EventDeleted: ["Event Deleted Successfully"],
  EventAdded: ["Event Added Successfully"],
  CategoryAleradyExist: ["Category Already Exist"],
  FaqAdded: ["Faq Added Successfully"],
  CallUpdated: ["Call Charge Updated Successfully"],
  CategoryAdded: ["Category Added Successfully"],
  CategoryDeleted: ["Category Deleted Successfully"],
  CategoryUpdated: ["Category Updated Successfully"],
  SubscriptionExists: ["Subscription Already Exist"],
  SubscriptionAdded: ["Subscription Added Successfully"],
  SubscriptionDeleted: ["Subscription Deleted Successfully"],
  SubscriptionUpdated: ["Subscription Updated Successfully"],
  AnnouncementDeleted: ["Announcement Deleted Successfully"],
  SubAdminAdded: ["SubAdmin Added Successfully"],
  Resolved: ["Resolved"],
  ContentUpdated: ["Content Updated Successfully"],
  EmailSent: ["Email Sent Successfully"],
  RepliedSuccessfully: ["Replied Successfully"],
  BrodcastSent: ["Broadcast sent successfully"],
  AdminProfileUpdated: ["Admin Profile Updated Successfully"],
  PasswordReset: ["Password reset successfully"],
  ServiceAleradyExist: ["Service Already Exist"],
  ServiceAdded: ["Service Added Successfully"],
  ServiceDeleted: ["Service Deleted Successfully"],
  ServiceUpdated: ["Service Updated Successfully"],
  EventNameAleradyExist: ["Event Name Already Exist"],
  EventUpdated: ["Event Updated Successfully"],
  SubcategoryAleradyExist: ["Subcategory Already Exist"],
  SubcategoryAdded: ["Subcategory Added Successfully"],
  SubcategoryDeleted: ["Subcategory Deleted Successfully"],
  SubcategoryUpdated: ["Subcategory Updated Successfully"],
  msgSubcategoryNotFound: ["Subcategory not Found"],
  FaqDeleted: ["Faq Deleted Successfully"],
  RatingDeleted: ["Rating Deleted Successfully"],
  DegreeAleradyExist: ["Degree Already Exist"],
  DegreeAdded: ["Degree Added Successfully"],
  DegreeUpdated: ["Degree Updated Successfully"],
  DegreeDeleted: ["Degree Deleted Successfully"],
  LanguageAleradyExist: ["Language Already Exist"],
  LanguageAdded: ["Language Added Successfully"],
  LanguageUpdated: ["Language Updated Successfully"],
  LanguageDeleted: ["Language Deleted Successfully"],
  DegreeNotFound: ["Degree not found"],
  LanguageNotFound: ["Language not found"],
  SubscriptionAleradyExist: ["Subscription Already Exist"],
  QuestionAleradyExist: ["Question Already Exist"],
  SubscriptionAdded: ["Subscription Added Successfully"],
  SubscriptionUpdated: ["Subscription Updated Successfully"],
  SubscriptionDeleted: ["Subscription Deleted Successfully"],
  SubscriptionNotFound: ["Subscription not found"],
  CityAleradyExist: ["City Already Exist"],
  CityAdded: ["City Added Successfully"],
  CityUpdated: ["City Updated Successfully"],
  CityDeleted: ["City Deleted Successfully"],
  RatingDeleted: ["Rating Deleted Successfully"],
  msdExpEyeUpdate: ["Expert Eye updated Successfully"],
};
module.exports = messages;
